#环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: "/zc-struct"
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    #baseDir
    basedir: "/data/zc-struct"

spring:
  application:
    name: "zc-struct"

  rabbitmq:
    host: "127.0.0.1"
    port: 5672
    username: "guest"
    password: "guest"
    virtual-host: "/"

  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&useAffectedRows=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://localhost:3306/test-slave?serverTimezone=GMT&useAffectedRows=true
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://localhost:3306/test-slave1?serverTimezone=GMT&useAffectedRows=true
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  # 邮件发送
  mail:
    host: smtp.qq.com
    username: 289894539@qq.com
    password: jwozcojtomssbibf
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactor:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
            fallback: false
          auth: true
        debug: true